import 'package:flutter/material.dart';

import '../../../../domain/constants/language_constants.dart';
import '../../../atoms/composite_component.dart';
import '../../../atoms/list_component.dart';
import '../../../atoms/paragraph_component.dart';
import '../../../atoms/title_component.dart';
import '../../widgets/appbar_with_leading.dart';



class CompositeTermsAndConditionsScreen extends StatelessWidget {
  const CompositeTermsAndConditionsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        appBar: MyAppBarWithLeading(title: translation(context)!.terms_and_conditions).getAppBar(),
        body: SingleChildScrollView(
          child: Padding(
            padding: const EdgeInsets.all(24.0),
            child: Column(
              children: [
                TitleComponent(translation(context)!.t_c__agreement_to_our_legal_terms_).render(),
                CompositeComponent(translation(context)!.t_c__introduction_, [
                  ParagraphComponent(translation(context)!.t_c__we_are_vistony_india_private_limited__doing_business_as_listoil___company____we____us___or__our____a_company_registered_in_india_at_a_1_118_second_floor_safdarjung_enclave_opposite_aashlok_hospital_new_delhi_dl_110029_in__delhi__delhi_110029___),
                  ParagraphComponent(translation(context)!.t_c__we_operate_the_mobile_application_qrcash__the__app____as_well_as_any_other_related_products_and_services_that_refer_or_link_to_these_legal_terms__the__legal_terms____collectively__the__services_____),
                  ParagraphComponent(translation(context)!.t_c__you_can_contact_us_by_phone_at_8619219450__email_at_vsharmalistoil_com__or_by_mail_to_f647__f647a__kushkera_industrial_area_riico__bhiwadi____bhiwadi__rajasthan_301707__india___),
                  ParagraphComponent(translation(context)!.t_c__these_legal_terms_constitute_a_legally_binding_agreement_made_between_you__whether_personally_or_on_behalf_of_an_entity___you____and_vistony_india_private_limited__concerning_your_access_to_and_use_of_the_services__you_agree_that_by_accessing_the_services__you_have_read__understood__and_agreed_to_be_bound_by_all_of_these_legal_terms__if_you_do_not_agree_with_all_of_these_legal_terms__then_you_are_expressly_prohibited_from_using_the_services_and_you_must_discontinue_use_immediately___),
                  ParagraphComponent(translation(context)!.t_c__we_will_provide_you_with_prior_notice_of_any_scheduled_changes_to_the_services_you_are_using__changes_to_legal_terms_will_become_effective_seven__7__days_after_the_notice_is_given__except_if_the_changes_apply_to_new_functionality__security_updates__bug_fixes__and_a_court_order__in_which_case_the_changes_will_be_effective_immediately__by_continuing_to_use_the_services_after_the_effective_date_of_any_changes__you_agree_to_be_bound_by_the_modified_terms__if_you_disagree_with_such_changes__you_may_terminate_services_as_per_the_section__term_and_termination____),
                  ParagraphComponent(translation(context)!.t_c__the_services_are_intended_for_users_who_are_at_least_18_years_old__persons_under_the_age_of_18_are_not_permitted_to_use_or_register_for_the_services___),
                  ParagraphComponent(translation(context)!.t_c__we_recommend_that_you_print_a_copy_of_these_legal_terms_for_your_records___),
                ]).render(),
                CompositeComponent(translation(context)!.t_c__table_of_contents_, [
                  TitleComponent(translation(context)!.t_c__index_),
                  ListComponent([
                    translation(context)!.t_c__1__our_services_,
                    translation(context)!.t_c__2__intellectual_property_rights_,
                    translation(context)!.t_c__3__user_representations_,
                    translation(context)!.t_c__4__user_registration_,
                    translation(context)!.t_c__5__prohibited_activities_,
                    translation(context)!.t_c__6__user_generated_contributions_,
                    translation(context)!.t_c__7__contribution_licence_,
                    translation(context)!.t_c__8__guidelines_for_reviews_,
                    translation(context)!.t_c__9__mobile_application_licence_,
                    translation(context)!.t_c__10__services_management_,
                    translation(context)!.t_c__11__privacy_policy_,
                    translation(context)!.t_c__12__term_and_termination_,
                    translation(context)!.t_c__13__modifications_and_interruptions_,
                    translation(context)!.t_c__14__governing_law_,
                    translation(context)!.t_c__15__dispute_resolution_,
                    translation(context)!.t_c__16__corrections_,
                    translation(context)!.t_c__17__disclaimer_,
                    translation(context)!.t_c__18__limitations_of_liability_,
                    translation(context)!.t_c__19__indemnification_,
                    translation(context)!.t_c__20__user_data_,
                    translation(context)!.t_c__21__electronic_communications__transactions__and_signatures_,
                    translation(context)!.t_c__22__miscellaneous_,
                    translation(context)!.t_c__23__contact_us_
                  ]),
                ]).render(),
                CompositeComponent(translation(context)!.t_c__1__our_services_, [
                  ParagraphComponent(translation(context)!.t_c__the_information_provided_when_using_the_services_is_not_intended_for_distribution_to_or_use_by_any_person_or_entity_in_any_jurisdiction_or_country_where_such_distribution_or_use_would_be_contrary_to_law_or_regulation_or_which_would_subject_us_to_any_registration_requirement_within_such_jurisdiction_or_country__accordingly__those_persons_who_choose_to_access_the_services_from_other_locations_do_so_on_their_own_initiative_and_are_solely_responsible_for_compliance_with_local_laws__if_and_to_the_extent_local_laws_are_applicable_),
                ]).render(),
                CompositeComponent(translation(context)!.t_c__2__intellectual_property_rights_, [
                  TitleComponent(translation(context)!.t_c__our_intellectual_propert_),
                  ParagraphComponent(translation(context)!.t_c__we_are_the_owner_or_the_licensee_of_all_intellectual_property_rights_in_our_services__including_all_source_code__databases__functionality__software__website_designs__audio__video__text__photographs__and_graphics_in_the_services__collectively__the__content____as_well_as_the_trademarks__service_marks__and_logos_contained_therein__the__mark_),
                  ParagraphComponent(translation(context)!.t_c__our_content_and_marks_are_protected_by_copyright_and_trademark_laws__and_various_other_intellectual_property_rights_and_unfair_competition_laws__and_treaties_in_the_united_states_and_around_the_worl_),
                  ParagraphComponent(translation(context)!.t_c__the_content_and_marks_are_provided_in_or_through_the_services__as_is__for_your_personal__non_commercial_use_or_internal_business_purpose_only_),
                  TitleComponent(translation(context)!.t_c__your_use_of_our_service_),
                  ParagraphComponent(translation(context)!.t_c__subject_to_your_compliance_with_these_legal_terms__including_the__prohibited_activities__section_below__we_grant_you_a_non_exclusive__non_transferable__revocable_licence_to_),
                  ListComponent([
                    translation(context)!.t_c__access_the_services__and_,
                    translation(context)!.t_c__download_or_print_a_copy_of_any_portion_of_the_content_to_which_you_have_properly_gained_access_,
                  ]),
                  ParagraphComponent(translation(context)!.t_c__solely_for_your_personal__non_commercial_use_or_internal_business_purpos_),
                  ParagraphComponent(translation(context)!.t_c__except_as_set_out_in_this_section_or_elsewhere_in_our_legal_terms__no_part_of_the_services_and_no_content_or_marks_may_be_copied__reproduced__aggregated__republished__uploaded__posted__publicly_displayed__encoded__translated__transmitted__distributed__sold__licensed__or_otherwise_exploited_for_any_commercial_purpose_whatsoever__without_our_express_prior_written_permission_),
                  ParagraphComponent(translation(context)!.t_c__if_you_wish_to_make_any_use_of_the_services__content__or_marks_other_than_as_set_out_in_this_section_or_elsewhere_in_our_legal_terms__please_address_your_request_to__vsharmalistoil_com__if_we_ever_grant_you_the_permission_to_post__reproduce__or_publicly_display_any_part_of_our_services_or_content__you_must_identify_us_as_the_owners_or_licensors_of_the_services__content__or_marks_and_ensure_that_any_copyright_or_proprietary_notice_appears_or_is_visible_on_posting__reproducing__or_displaying_our_content_),
                  ParagraphComponent(translation(context)!.t_c__we_reserve_all_rights_not_expressly_granted_to_you_in_and_to_the_services__content__and_marks_),
                  ParagraphComponent(translation(context)!.t_c__any_breach_of_these_intellectual_property_rights_will_constitute_a_material_breach_of_our_legal_terms_and_your_right_to_use_our_services_will_terminate_immediatel_),
                  TitleComponent(translation(context)!.t_c__your_submissions_and_contribution_),
                  ParagraphComponent(translation(context)!.t_c__please_review_this_section_and_the__prohibited_activities__section_carefully_prior_to_using_our_services_to_understand_the__a__rights_you_give_us_and__b__obligations_you_have_when_you_post_or_upload_any_content_through_the_services_),
                  CompositeComponent(translation(context)!.t_c__submissions__, [
                    ParagraphComponent(translation(context)!.t_c__by_directly_sending_us_any_question__comment__suggestion__idea__feedback__or_other_information_about_the_services___submissions____you_agree_to_assign_to_us_all_intellectual_property_rights_in_such_submission__you_agree_that_we_shall_own_this_submission_and_be_entitled_to_its_unrestricted_use_and_dissemination_for_any_lawful_purpose__commercial_or_otherwise__without_acknowledgment_or_compensation_to_you_),
                  ]),
                  CompositeComponent(translation(context)!.t_c__contributions__, [
                    ParagraphComponent(translation(context)!.t_c__the_services_may_invite_you_to_chat__contribute_to__or_participate_in_blogs__message_boards__online_forums__and_other_functionality_during_which_you_may_create__submit__post__display__transmit__publish__distribute__or_broadcast_content_and_materials_to_us_or_through_the_services__including_but_not_limited_to_text__writings__video__audio__photographs__music__graphics__comments__reviews__rating_suggestions__personal_information__or_other_material___contributions____any_submission_that_is_publicly_posted_shall_also_be_treated_as_a_contributio_),
                  ]),
                  ParagraphComponent(translation(context)!.t_c__you_understand_that_contributions_may_be_viewable_by_other_users_of_the_service_),
                  CompositeComponent(
                      translation(context)!.t_c__when_you_post_contributions__you_grant_us_a_licence__including_use_of_your_name__trademarks__and_logos___,
                      [
                        ParagraphComponent(translation(context)!.t_c__by_posting_any_contributions__you_grant_us_an_unrestricted__unlimited__irrevocable__perpetual__non_exclusive__transferable__royalty_free__fully_paid__worldwide_right__and_licence_to__use__copy__reproduce__distribute__sell__resell__publish__broadcast__retitle__store__publicly_perform__publicly_display__reformat__translate__excerpt__in_whole_or_in_part___and_exploit_your_contributions__including__without_limitation__your_image__name__and_voice__for_any_purpose__commercial__advertising__or_otherwise__to_prepare_derivative_works_of__or_incorporate_into_other_works__your_contributions__and_to_sublicence_the_licences_granted_in_this_section__our_use_and_distribution_may_occur_in_any_media_formats_and_through_any_media_channel_),
                        ParagraphComponent(translation(context)!.t_c__this_licence_includes_our_use_of_your_name__company_name__and_franchise_name__as_applicable__and_any_of_the_trademarks__service_marks__trade_names__logos__and_personal_and_commercial_images_you_provide_),
                        CompositeComponent(translation(context)!.t_c__you_are_responsible_for_what_you_post_or_upload__, [
                          ParagraphComponent(translation(context)!.t_c__by_sending_us_submissions_and_or_posting_contributions_through_any_part_of_the_services_or_making_contributions_accessible_through_the_services_by_linking_your_account_through_the_services_to_any_of_your_social_networking_accounts__yo_),
                          ListComponent([translation(context)!.t_c__confirm_that_you_have_read_and_agree_with_our__prohibited_activities__and_will_not_post__send__publish__upload__or_transmit_through_the_services_any_submission_nor_post_any_contribution_that_is_illegal__harassing__hateful__harmful__defamatory__obscene__bullying__abusive__discriminatory__threatening_to_any_person_or_group__sexually_explicit__false__inaccurate__deceitful__or_misleading__,
                            translation(context)!.t_c__to_the_extent_permissible_by_applicable_law__waive_any_and_all_moral_rights_to_any_such_submission_and_or_contribution__,
                            translation(context)!.t_c__warrant_that_any_such_submission_and_or_contributions_are_original_to_you_or_that_you_have_the_necessary_rights_and_licences_to_submit_such_submissions_and_or_contributions_and_that_you_have_full_authority_to_grant_us_the_above_mentioned_rights_in_relation_to_your_submissions_and_or_contributions__and_,
                            translation(context)!.t_c__warrant_and_represent_that_your_submissions_and_or_contributions_do_not_constitute_confidential_information___,

                          ]),
                          ParagraphComponent(translation(context)!.t_c__you_are_solely_responsible_for_your_submissions_and_or_contributions_and_you_expressly_agree_to_reimburse_us_for_any_and_all_losses_that_we_may_suffer_because_of_your_breach_of__a__this_section___b__any_third_party_s_intellectual_property_rights__or__c__applicable_law_),
                        ]),
                        CompositeComponent(
                            translation(context)!.t_c__we_may_remove_or_edit_your_content__, [
                          ParagraphComponent(translation(context)!.t_c__although_we_have_no_obligation_to_monitor_any_contributions__we_shall_have_the_right_to_remove_or_edit_any_contributions_at_any_time_without_notice_if_in_our_reasonable_opinion_we_consider_such_contributions_harmful_or_in_breach_of_these_legal_terms__if_we_remove_or_edit_any_such_contributions__we_may_also_suspend_or_disable_your_account_and_report_you_to_the_authorities_),
                        ]),
                      ]),
                ]).render(),
                CompositeComponent(translation(context)!.t_c__3__user_representations_, [
                  ParagraphComponent(translation(context)!.t_c__by_using_the_services__you_represent_and_warrant_that___1__all_registration_information_you_submit_will_be_true__accurate__current__and_complete___2__you_will_maintain_the_accuracy_of_such_information_and_promptly_update_such_registration_information_as_necessary___3__you_have_the_legal_capacity_and_you_agree_to_comply_with_these_legal_terms___4__you_are_not_a_minor_in_the_jurisdiction_in_which_you_reside___5__you_will_not_access_the_services_through_automated_or_non_human_means__whether_through_a_bot__script_or_otherwise___6__you_will_not_use_the_services_for_any_illegal_or_unauthorised_purpose__and__7__your_use_of_the_services_will_not_violate_any_applicable_law_or_regulatio_),
                  ParagraphComponent(translation(context)!.t_c__if_you_provide_any_information_that_is_untrue__inaccurate__not_current__or_incomplete__we_have_the_right_to_suspend_or_terminate_your_account_and_refuse_any_and_all_current_or_future_use_of_the_services__or_any_portion_thereof__),
                ]).render(),
                CompositeComponent(translation(context)!.t_c__4__user_registration_, [
                  ParagraphComponent(translation(context)!.t_c__you_may_be_required_to_register_to_use_the_services__you_agree_to_keep_your_password_confidential_and_will_be_responsible_for_all_use_of_your_account_and_password__we_reserve_the_right_to_remove__reclaim__or_change_a_username_you_select_if_we_determine__in_our_sole_discretion__that_such_username_is_inappropriate__obscene__or_otherwise_objectionable_),
                ]).render(),
                CompositeComponent(translation(context)!.t_c__5__prohibited_activities_, [
                  ParagraphComponent(translation(context)!.t_c__you_may_not_access_or_use_the_services_for_any_purpose_other_than_that_for_which_we_make_the_services_available__the_services_may_not_be_used_in_connection_with_any_commercial_endeavours_except_those_that_are_specifically_endorsed_or_approved_by_u_),
                  ParagraphComponent(translation(context)!.t_c__as_a_user_of_the_services__you_agree_not_to_),
                  ListComponent([
                    translation(context)!.t_c__systematically_retrieve_data_or_other_content_from_the_services_to_create_or_compile__directly_or_indirectly__a_collection__compilation__database__or_directory_without_written_permission_from_us__,
                    translation(context)!.t_c__trick__defraud__or_mislead_us_and_other_users__especially_in_any_attempt_to_learn_sensitive_account_information_such_as_user_passwords__,
                    translation(context)!.t_c__circumvent__disable__or_otherwise_interfere_with_security_related_features_of_the_services__including_features_that_prevent_or_restrict_the_use_or_copying_of_any_content_or_enforce_limitations_on_the_use_of_the_services_and_or_the_content_contained_therein__,
                    translation(context)!.t_c__disparage__tarnish__or_otherwise_harm__in_our_opinion__us_and_or_the_services__,
                    translation(context)!.t_c__disparage__tarnish__or_otherwise_harm__in_our_opinion__us_and_or_the_services__,
                    translation(context)!.t_c__use_any_information_obtained_from_the_services_in_order_to_harass__abuse__or_harm_another_person__,
                    translation(context)!.t_c__make_improper_use_of_our_support_services_or_submit_false_reports_of_abuse_or_misconduct__,
                    translation(context)!.t_c__use_the_services_in_a_manner_inconsistent_with_any_applicable_laws_or_regulations__,
                    translation(context)!.t_c__engage_in_unauthorised_framing_of_or_linking_to_the_services__,
                    translation(context)!.t_c__upload_or_transmit__or_attempt_to_upload_or_to_transmit__viruses__trojan_horses__or_other_material__including_excessive_use_of_capital_letters_and_spamming__continuous_posting_of_repetitive_text___that_interferes_with_any_party_s_uninterrupted_use_and_enjoyment_of_the_services_or_modifies__impairs__disrupts__alters__or_interferes_with_the_use__features__functions__operation__or_maintenance_of_the_services__,
                    translation(context)!.t_c__engage_in_any_automated_use_of_the_system__such_as_using_scripts_to_send_comments_or_messages__or_using_any_data_mining__robots__or_similar_data_gathering_and_extraction_tools__,
                    translation(context)!.t_c__delete_the_copyright_or_other_proprietary_rights_notice_from_any_content__,
                    translation(context)!.t_c__attempt_to_impersonate_another_user_or_person_or_use_the_username_of_another_user__,
                    translation(context)!.t_c__upload_or_transmit__or_attempt_to_upload_or_to_transmit__any_material_that_acts_as_a_passive_or_active_information_collection_or_transmission_mechanism__including_without_limitation__clear_graphics_interchange_formats___gifs____11_pixels__web_bugs__cookies__or_other_similar_devices__sometimes_referred_to_as__spyware__or__passive_collection_mechanisms__or__pcms____,
                    translation(context)!.t_c__interfere_with__disrupt__or_create_an_undue_burden_on_the_services_or_the_networks_or_services_connected_to_the_services__,
                    translation(context)!.t_c__harass__annoy__intimidate__or_threaten_any_of_our_employees_or_agents_engaged_in_providing_any_portion_of_the_services_to_you__,
                    translation(context)!.t_c__attempt_to_bypass_any_measures_of_the_services_designed_to_prevent_or_restrict_access_to_the_services__or_any_portion_of_the_services__,
                    translation(context)!.t_c__copy_or_adapt_the_services__software__including_but_not_limited_to_flash__php__html__javascript__or_other_code__,
                    translation(context)!.t_c__except_as_permitted_by_applicable_law__decipher__decompile__disassemble__or_reverse_engineer_any_of_the_software_comprising_or_in_any_way_making_up_a_part_of_the_services__,
                    translation(context)!.t_c__except_as_may_be_the_result_of_standard_search_engine_or_internet_browser_usage__use__launch__develop__or_distribute_any_automated_system__including_without_limitation__any_spider__robot__cheat_utility__scraper__or_offline_reader_that_accesses_the_services__or_use_or_launch_any_unauthorised_script_or_other_software__,
                    translation(context)!.t_c__use_a_buying_agent_or_purchasing_agent_to_make_purchases_on_the_services__,
                    translation(context)!.t_c__make_any_unauthorised_use_of_the_services__including_collecting_usernames_and_or_email_addresses_of_users_by_electronic_or_other_means_for_the_purpose_of_sending_unsolicited_email__or_creating_user_accounts_by_automated_means_or_under_false_pretences__,
                    translation(context)!.t_c__use_the_services_as_part_of_any_effort_to_compete_with_us_or_otherwise_use_the_services_and_or_the_content_for_any_revenue_generating_endeavour_or_commercial_enterprise__,
                    translation(context)!.t_c__use_the_services_to_advertise_or_offer_to_sell_goods_and_services__,
                  ])
                ]).render(),
                CompositeComponent(translation(context)!.t_c__6__user_generated_contributions_, [
                  ParagraphComponent(translation(context)!.t_c__the_services_may_invite_you_to_chat__contribute_to__or_participate_in_blogs__message_boards__online_forums__and_other_functionality__and_may_provide_you_with_the_opportunity_to_create__submit__post__display__transmit__perform__publish__distribute__or_broadcast_content_and_materials_to_us_or_on_the_services__including_but_not_limited_to_text__writings__video__audio__photographs__graphics__comments__suggestions__or_personal_information_or_other_material__collectively___contributions____contributions_may_be_viewable_by_other_users_of_the_services_and_through_third_party_websites__as_such__any_contributions_you_transmit_may_be_treated_as_non_confidential_and_non_proprietary__when_you_create_or_make_available_any_contributions__you_thereby_represent_and_warrant_that_),
                  ListComponent([
                    translation(context)!.t_c__the_creation__distribution__transmission__public_display__or_performance__and_the_accessing__downloading__or_copying_of_your_contributions_do_not_and_will_not_infringe_the_proprietary_rights__including_but_not_limited_to_the_copyright__patent__trademark__trade_secret__or_moral_rights_of_any_third_party__,
                    translation(context)!.t_c__you_are_the_creator_and_owner_of_or_have_the_necessary_licences__rights__consents__releases__and_permissions_to_use_and_to_authorise_us__the_services__and_other_users_of_the_services_to_use_your_contributions_in_any_manner_contemplated_by_the_services_and_these_legal_terms__,
                    translation(context)!.t_c__you_have_the_written_consent__release__and_or_permission_of_each_and_every_identifiable_individual_person_in_your_contributions_to_use_the_name_or_likeness_of_each_and_every_such_identifiable_individual_person_to_enable_inclusion_and_use_of_your_contributions_in_any_manner_contemplated_by_the_services_and_these_legal_terms__,
                    translation(context)!.t_c__your_contributions_are_not_false__inaccurate__or_misleading__,
                    translation(context)!.t_c__your_contributions_are_not_unsolicited_or_unauthorised_advertising__promotional_materials__pyramid_schemes__chain_letters__spam__mass_mailings__or_other_forms_of_solicitation__,
                    translation(context)!.t_c__your_contributions_are_not_obscene__lewd__lascivious__filthy__violent__harassing__libellous__slanderous__or_otherwise_objectionable__as_determined_by_us___,
                    translation(context)!.t_c__your_contributions_do_not_ridicule__mock__disparage__intimidate__or_abuse_anyone__,
                    translation(context)!.t_c__your_contributions_are_not_used_to_harass_or_threaten__in_the_legal_sense_of_those_terms__any_other_person_and_to_promote_violence_against_a_specific_person_or_class_of_people__,
                    translation(context)!.t_c__your_contributions_do_not_violate_any_applicable_law__regulation__or_rule__,
                    translation(context)!.t_c__your_contributions_do_not_violate_the_privacy_or_publicity_rights_of_any_third_party__,
                    translation(context)!.t_c__your_contributions_do_not_violate_any_applicable_law_concerning_child_pornography__or_otherwise_intended_to_protect_the_health_or_well_being_of_minors__,
                    translation(context)!.t_c__your_contributions_do_not_include_any_offensive_comments_that_are_connected_to_race__national_origin__gender__sexual_preference__or_physical_handica_,
                    translation(context)!.t_c__your_contributions_do_not_otherwise_violate__or_link_to_material_that_violates__any_provision_of_these_legal_terms__or_any_applicable_law_or_regulation___,
                  ]),
                  ParagraphComponent(translation(context)!.t_c__any_use_of_the_services_in_violation_of_the_foregoing_violates_these_legal_terms_and_may_result_in__among_other_things__termination_or_suspension_of_your_rights_to_use_the_services_),
                ]).render(),
                CompositeComponent(translation(context)!.t_c__7__contribution_licence_, [
                  ParagraphComponent(translation(context)!.t_c__by_posting_your_contributions_to_any_part_of_the_services__you_automatically_grant__and_you_represent_and_warrant_that_you_have_the_right_to_grant__to_us_an_unrestricted__unlimited__irrevocable__perpetual__non_exclusive__transferable__royalty_free__fully_paid__worldwide_right__and_licence_to_host__use__copy__reproduce__disclose__sell__resell__publish__broadcast__retitle__archive__store__cache__publicly_perform__publicly_display__reformat__translate__transmit__excerpt__in_whole_or_in_part___and_distribute_such_contributions__including__without_limitation__your_image_and_voice__for_any_purpose__commercial__advertising__or_otherwise__and_to_prepare_derivative_works_of__or_incorporate_into_other_works__such_contributions__and_grant_and_authorise_sublicences_of_the_foregoing__the_use_and_distribution_may_occur_in_any_media_formats_and_through_any_media_channel_),
                  ParagraphComponent(translation(context)!.t_c__this_licence_will_apply_to_any_form__media__or_technology_now_known_or_hereafter_developed__and_includes_our_use_of_your_name__company_name__and_franchise_name__as_applicable__and_any_of_the_trademarks__service_marks__trade_names__logos__and_personal_and_commercial_images_you_provide__you_waive_all_moral_rights_in_your_contributions__and_you_warrant_that_moral_rights_have_not_otherwise_been_asserted_in_your_contribution_),
                  ParagraphComponent(translation(context)!.t_c__we_do_not_assert_any_ownership_over_your_contributions__you_retain_full_ownership_of_all_of_your_contributions_and_any_intellectual_property_rights_or_other_proprietary_rights_associated_with_your_contributions__we_are_not_liable_for_any_statements_or_representations_in_your_contributions_provided_by_you_in_any_area_on_the_services__you_are_solely_responsible_for_your_contributions_to_the_services_and_you_expressly_agree_to_exonerate_us_from_any_and_all_responsibility_and_to_refrain_from_any_legal_action_against_us_regarding_your_contribution_),
                  ParagraphComponent(translation(context)!.t_c__we_have_the_right__in_our_sole_and_absolute_discretion___1__to_edit__redact__or_otherwise_change_any_contributions___2__to_re_categorise_any_contributions_to_place_them_in_more_appropriate_locations_on_the_services__and__3__to_pre_screen_or_delete_any_contributions_at_any_time_and_for_any_reason__without_notice__we_have_no_obligation_to_monitor_your_contributions_),
                ]).render(),
                CompositeComponent(translation(context)!.t_c__8__guidelines_for_reviews_, [
                  ParagraphComponent(translation(context)!.t_c__we_may_provide_you_areas_on_the_services_to_leave_reviews_or_ratings__when_posting_a_review__you_must_comply_with_the_following_criteria___1__you_should_have_firsthand_experience_with_the_person_entity_being_reviewed___2__your_reviews_should_not_contain_offensive_profanity__or_abusive__racist__offensive__or_hateful_language___3__your_reviews_should_not_contain_discriminatory_references_based_on_religion__race__gender__national_origin__age__marital_status__sexual_orientation__or_disability___4__your_reviews_should_not_contain_references_to_illegal_activity___5__you_should_not_be_affiliated_with_competitors_if_posting_negative_reviews___6__you_should_not_make_any_conclusions_as_to_the_legality_of_conduct___7__you_may_not_post_any_false_or_misleading_statements__and__8__you_may_not_organise_a_campaign_encouraging_others_to_post_reviews__whether_positive_or_negativ_),
                  ParagraphComponent(translation(context)!.t_c__we_may_accept__reject__or_remove_reviews_in_our_sole_discretion__we_have_absolutely_no_obligation_to_screen_reviews_or_to_delete_reviews__even_if_anyone_considers_reviews_objectionable_or_inaccurate__reviews_are_not_endorsed_by_us__and_do_not_necessarily_represent_our_opinions_or_the_views_of_any_of_our_affiliates_or_partners__we_do_not_assume_liability_for_any_review_or_for_any_claims__liabilities__or_losses_resulting_from_any_review__by_posting_a_review__you_hereby_grant_to_us_a_perpetual__non_exclusive__worldwide__royalty_free__fully_paid__assignable__and_sublicensable_right_and_licence_to_reproduce__modify__translate__transmit_by_any_means__display__perform__and_or_distribute_all_content_relating_to_review____),
                ]).render(),
                CompositeComponent(translation(context)!.t_c__9__mobile_application_licence_, [
                  TitleComponent(translation(context)!.t_c__use_licenc_),
                  ParagraphComponent(translation(context)!.t_c__if_you_access_the_services_via_the_app__then_we_grant_you_a_revocable__non_exclusive__non_transferable__limited_right_to_install_and_use_the_app_on_wireless_electronic_devices_owned_or_controlled_by_you__and_to_access_and_use_the_app_on_such_devices_strictly_in_accordance_with_the_terms_and_conditions_of_this_mobile_application_licence_contained_in_these_legal_terms__you_shall_not___1__except_as_permitted_by_applicable_law__decompile__reverse_engineer__disassemble__attempt_to_derive_the_source_code_of__or_decrypt_the_app___2__make_any_modification__adaptation__improvement__enhancement__translation__or_derivative_work_from_the_app___3__violate_any_applicable_laws__rules__or_regulations_in_connection_with_your_access_or_use_of_the_app___4__remove__alter__or_obscure_any_proprietary_notice__including_any_notice_of_copyright_or_trademark__posted_by_us_or_the_licensors_of_the_app___5__use_the_app_for_any_revenue_generating_endeavour__commercial_enterprise__or_other_purpose_for_which_it_is_not_designed_or_intended___6__make_the_app_available_over_a_network_or_other_environment_permitting_access_or_use_by_multiple_devices_or_users_at_the_same_time___7__use_the_app_for_creating_a_product__service__or_software_that_is__directly_or_indirectly__competitive_with_or_in_any_way_a_substitute_for_the_app___8__use_the_app_to_send_automated_queries_to_any_website_or_to_send_any_unsolicited_commercial_email__or__9__use_any_proprietary_information_or_any_of_our_interfaces_or_our_other_intellectual_property_in_the_design__development__manufacture__licensing__or_distribution_of_any_applications__accessories__or_devices_for_use_with_the_app_),
                  TitleComponent(translation(context)!.t_c__apple_and_android_),
                  ParagraphComponent(translation(context)!.t_c__the_following_terms_apply_when_you_use_the_app_obtained_from_either_the_apple_store_or_google_play__each_an__app_distributor___to_access_the_services___1__the_licence_granted_to_you_for_our_app_is_limited_to_a_non_transferable_licence_to_use_the_application_on_a_device_that_utilises_the_apple_ios_or_android_operating_systems__as_applicable__and_in_accordance_with_the_usage_rules_set_forth_in_the_applicable_app_distributor_s_terms_of_service___2__we_are_responsible_for_providing_any_maintenance_and_support_services_with_respect_to_the_app_as_specified_in_the_terms_and_conditions_of_this_mobile_application_licence_contained_in_these_legal_terms_or_as_otherwise_required_under_applicable_law__and_you_acknowledge_that_each_app_distributor_has_no_obligation_whatsoever_to_furnish_any_maintenance_and_support_services_with_respect_to_the_app___3__in_the_event_of_any_failure_of_the_app_to_conform_to_any_applicable_warranty__you_may_notify_the_applicable_app_distributor__and_the_app_distributor__in_accordance_with_its_terms_and_policies__may_refund_the_purchase_price__if_any__paid_for_the_app__and_to_the_maximum_extent_permitted_by_applicable_law__the_app_distributor_will_have_no_other_warranty_obligation_whatsoever_with_respect_to_the_app___4__you_represent_and_warrant_that__i__you_are_not_located_in_a_country_that_is_subject_to_a_us_government_embargo__or_that_has_been_designated_by_the_us_government_as_a__terrorist_supporting__country_and__ii__you_are_not_listed_on_any_us_government_list_of_prohibited_or_restricted_parties___5__you_must_comply_with_applicable_third_party_terms_of_agreement_when_using_the_app__e_g__if_you_have_a_voip_application__then_you_must_not_be_in_violation_of_their_wireless_data_service_agreement_when_using_the_app__and__6__you_acknowledge_and_agree_that_the_app_distributors_are_third_party_beneficiaries_of_the_terms_and_conditions_in_this_mobile_application_licence_contained_in_these_legal_terms__and_that_each_app_distributor_will_have_the_right__and_will_be_deemed_to_have_accepted_the_right__to_enforce_the_terms_and_conditions_in_this_mobile_application_licence_contained_in_these_legal_terms_against_you_as_a_third_party_beneficiary_thereof_),
                ]).render(),
                CompositeComponent(translation(context)!.t_c__10__services_management_, [
                  ParagraphComponent(translation(context)!.t_c__we_reserve_the_right__but_not_the_obligation__to___1__monitor_the_services_for_violations_of_these_legal_terms___2__take_appropriate_legal_action_against_anyone_who__in_our_sole_discretion__violates_the_law_or_these_legal_terms__including_without_limitation__reporting_such_user_to_law_enforcement_authorities___3__in_our_sole_discretion_and_without_limitation__refuse__restrict_access_to__limit_the_availability_of__or_disable__to_the_extent_technologically_feasible__any_of_your_contributions_or_any_portion_thereof___4__in_our_sole_discretion_and_without_limitation__notice__or_liability__to_remove_from_the_services_or_otherwise_disable_all_files_and_content_that_are_excessive_in_size_or_are_in_any_way_burdensome_to_our_systems__and__5__otherwise_manage_the_services_in_a_manner_designed_to_protect_our_rights_and_property_and_to_facilitate_the_proper_functioning_of_the_services____),
                ]).render(),
                CompositeComponent(translation(context)!.t_c__11__privacy_policy_, [
                  ParagraphComponent(translation(context)!.t_c__we_care_about_data_privacy_and_security__please_review_our_privacy_policy__http___www_listoil_com_privacy__by_using_the_services__you_agree_to_be_bound_by_our_privacy_policy__which_is_incorporated_into_these_legal_terms__please_be_advised_the_services_are_hosted_in_peru__if_you_access_the_services_from_any_other_region_of_the_world_with_laws_or_other_requirements_governing_personal_data_collection__use__or_disclosure_that_differ_from_applicable_laws_in_peru__then_through_your_continued_use_of_the_services__you_are_transferring_your_data_to_peru__and_you_expressly_consent_to_have_your_data_transferred_to_and_processed_in_peru____),
                ]).render(),
                CompositeComponent(translation(context)!.t_c__12__term_and_termination_, [
                  ParagraphComponent(translation(context)!.t_c__these_legal_terms_shall_remain_in_full_force_and_effect_while_you_use_the_services__without_limiting_any_other_provision_of_these_legal_terms__we_reserve_the_right_to__in_our_sole_discretion_and_without_notice_or_liability__deny_access_to_and_use_of_the_services__including_blocking_certain_ip_addresses___to_any_person_for_any_reason_or_for_no_reason__including_without_limitation_for_breach_of_any_representation__warranty__or_covenant_contained_in_these_legal_terms_or_of_any_applicable_law_or_regulation__we_may_terminate_your_use_or_participation_in_the_services_or_delete_your_account_and_any_content_or_information_that_you_posted_at_any_time__without_warning__in_our_sole_discretion___),
                  ParagraphComponent(translation(context)!.t_c__if_we_terminate_or_suspend_your_account_for_any_reason__you_are_prohibited_from_registering_and_creating_a_new_account_under_your_name__a_fake_or_borrowed_name__or_the_name_of_any_third_party__even_if_you_may_be_acting_on_behalf_of_the_third_party__in_addition_to_terminating_or_suspending_your_account__we_reserve_the_right_to_take_appropriate_legal_action__including_without_limitation_pursuing_civil__criminal__and_injunctive_redress____),
                ]).render(),
                CompositeComponent(translation(context)!.t_c__13__modifications_and_interruptions_, [
                  ParagraphComponent(translation(context)!.t_c__we_reserve_the_right_to_change__modify__or_remove_the_contents_of_the_services_at_any_time_or_for_any_reason_at_our_sole_discretion_without_notice__however__we_have_no_obligation_to_update_any_information_on_our_services__we_will_not_be_liable_to_you_or_any_third_party_for_any_modification__price_change__suspension__or_discontinuance_of_the_services___),
                  ParagraphComponent(translation(context)!.t_c__we_cannot_guarantee_the_services_will_be_available_at_all_times__we_may_experience_hardware__software__or_other_problems_or_need_to_perform_maintenance_related_to_the_services__resulting_in_interruptions__delays__or_errors__we_reserve_the_right_to_change__revise__update__suspend__discontinue__or_otherwise_modify_the_services_at_any_time_or_for_any_reason_without_notice_to_you__you_agree_that_we_have_no_liability_whatsoever_for_any_loss__damage__or_inconvenience_caused_by_your_inability_to_access_or_use_the_services_during_any_downtime_or_discontinuance_of_the_services__nothing_in_these_legal_terms_will_be_construed_to_obligate_us_to_maintain_and_support_the_services_or_to_supply_any_corrections__updates__or_releases_in_connection_therewith___),
                ]).render(),
                CompositeComponent(translation(context)!.t_c__14__governing_law_, [
                  ParagraphComponent(translation(context)!.t_c__these_legal_terms_shall_be_governed_by_and_defined_following_the_laws_of_india__vistony_india_private_limited_and_yourself_irrevocably_consent_that_the_courts_of_india_shall_have_exclusive_jurisdiction_to_resolve_any_dispute_which_may_arise_in_connection_with_these_legal_terms___),
                ]).render(),
                CompositeComponent(translation(context)!.t_c__15__dispute_resolution_, [
                  ParagraphComponent(translation(context)!.t_c__you_agree_to_irrevocably_submit_all_disputes_related_to_these_legal_terms_or_the_legal_relationship_established_by_these_legal_terms_to_the_jurisdiction_of_the_india_courts__vistony_india_private_limited_shall_also_maintain_the_right_to_bring_proceedings_as_to_the_substance_of_the_matter_in_the_courts_of_the_country_where_you_reside_or__if_these_legal_terms_are_entered_into_in_the_course_of_your_trade_or_profession__the_state_of_your_principal_place_of_business___),
                ]).render(),
                CompositeComponent(translation(context)!.t_c__16__corrections_, [
                  ParagraphComponent(translation(context)!.t_c__there_may_be_information_on_the_services_that_contains_typographical_errors__inaccuracies__or_omissions__including_descriptions__pricing__availability__and_various_other_information__we_reserve_the_right_to_correct_any_errors__inaccuracies__or_omissions_and_to_change_or_update_the_information_on_the_services_at_any_time__without_prior_notice____),
                ]).render(),
                CompositeComponent(translation(context)!.t_c__17__disclaimer_, [
                  ParagraphComponent(translation(context)!.t_c__the_services_are_provided_on_an_as_is_and_as_available_basis__you_agree_that_your_use_of_the_services_will_be_at_your_sole_risk__to_the_fullest_extent_permitted_by_law__we_disclaim_all_warranties__express_or_implied__in_connection_with_the_services_and_your_use_thereof__including__without_limitation__the_implied_warranties_of_merchantability__fitness_for_a_particular_purpose__and_non_infringement__we_make_no_warranties_or_representations_about_the_accuracy_or_completeness_of_the_services__content_or_the_content_of_any_websites_or_mobile_applications_linked_to_the_services_and_we_will_assume_no_liability_or_responsibility_for_any__1__errors__mistakes__or_inaccuracies_of_content_and_materials___2__personal_injury_or_property_damage__of_any_nature_whatsoever__resulting_from_your_access_to_and_use_of_the_services___3__any_unauthorised_access_to_or_use_of_our_secure_servers_and_or_any_and_all_personal_information_and_or_financial_information_stored_therein___4__any_interruption_or_cessation_of_transmission_to_or_from_the_services___5__any_bugs__viruses__trojan_horses__or_the_like_which_may_be_transmitted_to_or_through_the_services_by_any_third_party__and_or__6__any_errors_or_omissions_in_any_content_and_materials_or_for_any_loss_or_damage_of_any_kind_incurred_as_a_result_of_the_use_of_any_content_posted__transmitted__or_otherwise_made_available_via_the_services__we_do_not_warrant__endorse__guarantee__or_assume_responsibility_for_any_product_or_service_advertised_or_offered_by_a_third_party_through_the_services__any_hyperlinked_website__or_any_website_or_mobile_application_featured_in_any_banner_or_other_advertising__and_we_will_not_be_a_party_to_or_in_any_way_be_responsible_for_monitoring_any_transaction_between_you_and_any_third_party_providers_of_products_or_services__as_with_the_purchase_of_a_product_or_service_through_any_medium_or_in_any_environment__you_should_use_your_best_judgement_and_exercise_caution_where_appropriate____),
                ]).render(),
                CompositeComponent(translation(context)!.t_c__18__limitations_of_liability_, [
                  ParagraphComponent(translation(context)!.t_c__in_no_event_will_we_or_our_directors__employees__or_agents_be_liable_to_you_or_any_third_party_for_any_direct__indirect__consequential__exemplary__incidental__special__or_punitive_damages__including_lost_profit__lost_revenue__loss_of_data__or_other_damages_arising_from_your_use_of_the_services__even_if_we_have_been_advised_of_the_possibility_of_such_damages__notwithstanding_anything_to_the_contrary_contained_herein__our_liability_to_you_for_any_cause_whatsoever_and_regardless_of_the_form_of_the_action__will_at_all_times_be_limited_to_the_amount_paid__if_any__by_you_to_us_during_the_six__6__month_period_prior_to_any_cause_of_action_arising__certain_us_state_laws_and_international_laws_do_not_allow_limitations_on_implied_warranties_or_the_exclusion_or_limitation_of_certain_damages__if_these_laws_apply_to_you__some_or_all_of_the_above_disclaimers_or_limitations_may_not_apply_to_you__and_you_may_have_additional_rights____),
                ]).render(),
                CompositeComponent(translation(context)!.t_c__19__indemnification_, [
                  ParagraphComponent(translation(context)!.t_c__you_agree_to_defend__indemnify__and_hold_us_harmless__including_our_subsidiaries__affiliates__and_all_of_our_respective_officers__agents__partners__and_employees__from_and_against_any_loss__damage__liability__claim__or_demand__including_reasonable_attorneys__fees_and_expenses__made_by_any_third_party_due_to_or_arising_out_of___1__your_contributions___2__use_of_the_services___3__breach_of_these_legal_terms___4__any_breach_of_your_representations_and_warranties_set_forth_in_these_legal_terms___5__your_violation_of_the_rights_of_a_third_party__including_but_not_limited_to_intellectual_property_rights__or__6__any_overt_harmful_act_toward_any_other_user_of_the_services_with_whom_you_connected_via_the_services__notwithstanding_the_foregoing__we_reserve_the_right__at_your_expense__to_assume_the_exclusive_defence_and_control_of_any_matter_for_which_you_are_required_to_indemnify_us__and_you_agree_to_cooperate__at_your_expense__with_our_defence_of_such_claims__we_will_use_reasonable_efforts_to_notify_you_of_any_such_claim__action__or_proceeding_which_is_subject_to_this_indemnification_upon_becoming_aware_of_it____),
                ]).render(),
                CompositeComponent(translation(context)!.t_c__20__user_data_, [
                  ParagraphComponent(translation(context)!.t_c__we_will_maintain_certain_data_that_you_transmit_to_the_services_for_the_purpose_of_managing_the_performance_of_the_services__as_well_as_data_relating_to_your_use_of_the_services__although_we_perform_regular_routine_backups_of_data__you_are_solely_responsible_for_all_data_that_you_transmit_or_that_relates_to_any_activity_you_have_undertaken_using_the_services__you_agree_that_we_shall_have_no_liability_to_you_for_any_loss_or_corruption_of_any_such_data__and_you_hereby_waive_any_right_of_action_against_us_arising_from_any_such_loss_or_corruption_of_such_data____),
                ]).render(),
                CompositeComponent(
                    translation(context)!.t_c__21__electronic_communications__transactions__and_signatures_,
                    [
                      ParagraphComponent(translation(context)!.t_c__visiting_the_services__sending_us_emails__and_completing_online_forms_constitute_electronic_communications__you_consent_to_receive_electronic_communications__and_you_agree_that_all_agreements__notices__disclosures__and_other_communications_we_provide_to_you_electronically__via_email_and_on_the_services__satisfy_any_legal_requirement_that_such_communication_be_in_writing__you_hereby_agree_to_the_use_of_electronic_signatures__contracts__orders__and_other_records__and_to_electronic_delivery_of_notices__policies__and_records_of_transactions_initiated_or_completed_by_us_or_via_the_services__you_hereby_waive_any_rights_or_requirements_under_any_statutes__regulations__rules__ordinances__or_other_laws_in_any_jurisdiction_which_require_an_original_signature_or_delivery_or_retention_of_non_electronic_records__or_to_payments_or_the_granting_of_credits_by_any_means_other_than_electronic_means____),
                    ]).render(),
                CompositeComponent(translation(context)!.t_c__22__miscellaneous_, [
                  ParagraphComponent(translation(context)!.t_c__these_legal_terms_and_any_policies_or_operating_rules_posted_by_us_on_the_services_or_in_respect_to_the_services_constitute_the_entire_agreement_and_understanding_between_you_and_us__our_failure_to_exercise_or_enforce_any_right_or_provision_of_these_legal_terms_shall_not_operate_as_a_waiver_of_such_right_or_provision__these_legal_terms_operate_to_the_fullest_extent_permissible_by_law__we_may_assign_any_or_all_of_our_rights_and_obligations_to_others_at_any_time__we_shall_not_be_responsible_or_liable_for_any_loss__damage__delay__or_failure_to_act_caused_by_any_cause_beyond_our_reasonable_control__if_any_provision_or_part_of_a_provision_of_these_legal_terms_is_determined_to_be_unlawful__void__or_unenforceable__that_provision_or_part_of_the_provision_is_deemed_severable_from_these_legal_terms_and_does_not_affect_the_validity_and_enforceability_of_any_remaining_provisions__there_is_no_joint_venture__partnership__employment_or_agency_relationship_created_between_you_and_us_as_a_result_of_these_legal_terms_or_use_of_the_services__you_agree_that_these_legal_terms_will_not_be_construed_against_us_by_virtue_of_having_drafted_them__you_hereby_waive_any_and_all_defences_you_may_have_based_on_the_electronic_form_of_these_legal_terms_and_the_lack_of_signing_by_the_parties_hereto_to_execute_these_legal_terms____),
                ]).render(),
                CompositeComponent(translation(context)!.t_c__23__contact_us_, [
                  ParagraphComponent(translation(context)!.t_c__in_order_to_resolve_a_complaint_regarding_the_services_or_to_receive_further_information_regarding_use_of_the_services__please_contact_us_at___),
                  ListComponent([translation(context)!.t_c__vistony_india_private_limited_,
                    translation(context)!.t_c__f647__f647a__kushkera_industrial_area_riico__bhiwadi__,
                    translation(context)!.t_c__bhiwadi__rajasthan_301707_,
                    translation(context)!.t_c__india_,
                    translation(context)!.t_c__phone__8619219450_,
                    translation(context)!.t_c__vsharmalistoil_com_,
                  ]),
                ]).render(),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
