name: qr_save_scan
description: "Listoil all rights are reserved"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.10+11


environment:
  sdk: '>=3.3.0-174.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  animated_text_kit: ^4.2.2
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  geolocator: ^10.1.0
  http: ^1.1.2
  flutter_svg: ^2.0.9
  local_auth: ^2.1.7
  transparent_image: ^2.0.1
  location: ^5.0.3
  image_picker: ^1.0.5
  flutter_countdown_timer: ^4.1.0
  youtube_player_iframe: ^4.0.4
  flutter_rating_bar: ^4.0.1
  curved_navigation_bar: ^1.0.3
  qr_flutter: ^4.1.0
  flutter_localization: ^0.2.0
  google_fonts: ^6.1.0
  http_parser: ^4.0.2
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1
  fancy_password_field: ^2.0.2
  font_awesome_flutter: ^10.6.0
  smart_auth: ^1.1.1
  pin_code_fields: ^8.0.1
  mobile_scanner: ^3.5.5
  native_auth: ^1.0.6
  url_launcher: ^6.2.2
  intl: ^0.18.0
  lottie: ^2.7.0
  awesome_dialog: ^3.2.0
  flutter_email_sender: ^6.0.2
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.8

  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2

flutter_gen:
  output: lib/presentation/core/util/constantes/

flutter_native_splash:
  android: true
  ios: true
  web: true
  color: #FFFFFF
  color_dark: #121212
  background_image: "assets/icons/ic_launcher.png"  # Asegúrate de proporcionar la extensión del archivo


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ic_launcher.png"
  min_sdk_android: 21
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  generate: true


  assets:
    - assets/images/
    - assets/videos/
    - assets/gifs/
    - assets/icons/
    - assets/lottie/
    - assets/
    - assets/fonts/